### ISSUE TITLE
Convert wav2vec2 fine tuned model to torch script model

### ISSUE THREAD

**Issue by ShahzebAli42** [Open-Speech-EkStep/vakyansh-models#12]
I am unable to convert wav2vec2 fine tuned model to torchscript. I want to prune/quantize or shorten the size of the model so that i can load as many models as i can.
Can anyone tell me how to do that? 

I have followed vakyansh/convert_hf scripts but couldn't do so because of the errors.

**Comment by anjul1008** [comment]
Hi @harveenchadha,
I'm trying to convert wav2vec2 model to onnx for inference use.
I face below error, can you please help me
`
    print('Exporting onnx model to', onnx_model)
    torch.onnx.export(
        model,                                                  # model being run
        # tuple(encoder_input.values()),
        (
            encoder_input['source'],                            # model input (or a tuple for multiple inputs)
            encoder_input['padding_mask']
        ),     
        onnx_model,                                             # where to save the model (can be a file or file-like object)
        opset_version=12,                                       # the ONNX version to export the model to
        verbose=True,
        do_constant_folding=True,                               # whether to execute constant folding for optimization
        input_names=[                                           # the model's input names
                        'feats',                         
                        'input_mask'
                    ],
        output_names=[                                          # the model's output names
                        'encoder_out', 
                        'encoder_padding_mask', 
                        'padding_mask' 
                    ],                   
        dynamic_axes={
                        'feats': {0: 'batch_size', 1: 'max_seq_len'},        # variable length axes
                        'input_mask': {0: 'batch_size', 1: 'max_seq_len'}
                    }
    )

error:
Exporting onnx model to model.onnx
Traceback (most recent call last):
  File "generate_onnx_model.py", line 191, in <module>
    result = main(args_local)
  File "generate_onnx_model.py", line 173, in main
    with torch.no_grad(): generate_onnx_model(args_local, model, sample)
  File "generate_onnx_model.py", line 125, in generate_onnx_model
    torch.onnx.export(
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 1 positional argument but 3 were given
`

Same error wile converting to torchscript
`
    jit_module = torch.jit.trace(model, tuple(encoder_input.values()), strict=False, check_trace=False)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda/envs/fairseq_fb_18-11-21/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 1 positional argument but 3 were given
`

**Comment by harveenchadha** [comment]
The errors for hf_scripts have been fixed now!
